### ISSUE TITLE
Provide custom app source/in-depth guide

### ISSUE THREAD

**Issue by oeed** [khanhas/spicetify-cli#117]
Hey! I've got an idea for a highly customised albums page I want to add and a custom app seems the way to do this. Looking through the code for the Reddit and bookmarks apps it seems like you're using a lot of Spotify APIs which I imagine are undocumented.

Would it be possible to link the source (I assume it's TypeScript/Babelifed) for bundle? Alternatively, is there any documentation Spotify provides? It seems to include 'spotify-cosmos-api', but I can't seem to find it anywhere online.

**Comment by khanhas** [comment]
1. At current version, apps sources were bundled and minified to unreadable state and somewhat, obscure to modify. You need to find old version app sources which was only bundled. Function and variable names were kept and packages were clearly numbered. On then, you are able to speculate, reverse-engineer and do some modification on them.
I didn't find any official link to old version installer but there is unofficial and adblocked one on github. This is the last version that sources weren't minified:
https://github.com/CHEF-KOCH/Spotify-Ad-free/releases/download/0.7/SpotifyFullSetup.exe
After installed, please DO NOT run the Spotify executable, log in or use it. You are at risk of violating Spotify's TOS if you do so. Just copy SPA zip packages and uninstall that version immediately.

2. All JS packages relating to Spotify API are internally used by Spotify team. I don't think they will ever publish for everyone to use.

3. I did write some tips here: https://github.com/khanhas/Spicetify/wiki/App . They might help you gain some traction.

I will close this issue for now since it's not an issue. But if you have any question, please drop it here, I will try my best to answer as soon as possible.
