### ISSUE TITLE
Create Documentation Website

### ISSUE THREAD

**Issue by afonsojramos** [khanhas/spicetify-cli#1198]
The GitHub wiki is very limited and also blocks the community from contributing since GitHub does not allow for PRs to it. As such, we should create a `/docs` folder that deploys to a Vercel website.

**Comment by itsmeow** [comment]
Community wiki contribution is actually a thing, it just has to be enabled in the repository settings.

**Comment by afonsojramos** [comment]
@itsmeow me and @khanhas checked and it doesn't seem that it is possible (https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github). So I think I will continue with the development of a wiki site.

**Comment by Ballasi** [comment]
Is there any update on this? If it isn't the case, you probably would want to take a look at [mdbook](https://github.com/rust-lang/mdBook) which is aimed at tackling exactly this problem and publish your documentation to GitHub Pages. This is exactly what I did [in a personal project](https://github.com/osbx/wiki/) in the past and it worked wonderfully. [Here](https://wiki.osbx.org/storyboard/osb) is an example of an output mdbook can do. I can help set it up if you are interested.

**Comment by itsmeow** [comment]
Might I suggest this: https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/

**Comment by Ballasi** [comment]
I feel like mdbook is the easiest SSG/documentation generator to pick up and deploy and it has a clear and very user-friendly result. In my usage, you only have to run `$ mdbook init <name>`, edit the .md files in `src/` and serve or build and deploy your website and tada, it works and it's beautiful. The GitHub Actions I did for this it quite straight-forward too. On the other hand though, there is no theme customization other than the out-of-the-box color scheming, but personally, I really prefer the look of mdbook's results than any other SSG (very sleek and uncomplexified look in my opinion), that's why I chose it. You can also add custom CSS/JS but I don't think you can modify the HTML structure.

I didn't knew of docusaurus before, it looks a bit more convoluted but allows for more customization. Looks like a solid option to go for in my opinion.

Does GitHub's docs system have any way to create chapters and such? It's written that "This will generate the most basic HTML output", but is there any way to have some sort of left bar showing every categories/pages? I guess this is supposed to be kept on the index.md file. I tried to check out projects using this system but I couldn't find one. I will try deploying one on a private repo to see how that works.

**Comment by afonsojramos** [comment]
Sooo, the first version of the Spicetify Documentation website is now live I guess! 

Also bought a cool domain, so you can check it out here: https://spicetify.app/

I'm not the best frontend developer, so I'll leave the best part for the community. You can contribute to the project here: https://github.com/afonsojramos/spicetify-docs

**Comment by khanhas** [comment]
Great work @afonsojramos! This looks really awesome
Thank you very much for spending your time making this!

**Comment by afonsojramos** [comment]
Still a work in progress, but I suppose it's definitely a start!

@khanhas I see you already updated the links from the readme :eyes: Maybe we could also add the link to this repo's about section!
