### ISSUE TITLE
[Suggestion] Update wiki page to mention third possible theme location

### ISSUE THREAD

**Issue by George-lewis** [khanhas/spicetify-cli#127]
[This wiki page](https://github.com/khanhas/spicetify-cli/wiki/Customization) mentions two possible locations for themes to be placed, however on my system (Arch / AUR install) it took quite a bit of searching to discover that there seems to be a third possible location: `/usr/share/spicetify-cli/Themes/`. This was exposed to me through running `spicetify path` however I think we should note it on the wiki page.

**Comment by khanhas** [comment]
I did mention it in the second option in Themes section: https://github.com/khanhas/spicetify-cli/wiki/Customization#themes
Even so, putting theme in that folder is not recommended. Because most likely, it will be gone when you upgrade `spicetify-cli`. 
Also writting into it requires permission while writting into the one in config folder doesn't.

**Comment by George-lewis** [comment]
> It is the second option in Themes section

My mistake then. For me the executable is in `/usr/bin` and the spicetify folder is in `/usr/share` but I'll just assume these are linked somehow.

Should I be copying the default theme into `~/.config/spicetify/Themes`?

**Comment by khanhas** [comment]
You should if you did any modification on it.
