### ISSUE TITLE
Feature Request -- Add Songs from Friend Activity to Queue

### ISSUE THREAD

**Issue by invious** [khanhas/spicetify-cli#133]
I was thinking it would be cool to automatically add the songs that a friend that has really good taste is listening to, as they listen to them, and show up in the Friend Activity section.

I don't know if it's possible using the current API to do this, but if it is I could take a crack at it.

**Comment by khanhas** [comment]
You can always make your own extension.  
Use link below to request friends list and their tracks:
```javascript
Spicetify.CosmosAPI.resolver.get("hm://presence-view/v1/buddylist", (err, raw) => {
	const response = JSON.parse(raw._body);
	console.log(response);
})
```

**Comment by PPillau** [comment]
@khanhas is the second api call (presence2/user/xxxxx) still working? Because I just tried it an got a 403 Request not allowed. Any idea what kind of authorization I need? Im using the "Bearer WebAccessToken" header for now. 
Do you now if there is a limit to how often I can call the first api-route (presence-view/v1/buddylist) before I get blocked or something?

**Comment by khanhas** [comment]
1. It still works fine on mine. And I don't think you need any header to call the API. Are you using the exact same code I gave?
2. I honestly don't know.
