### ISSUE TITLE
Are you sure? ("Export PATH")

### ISSUE THREAD

**Issue by Reikimann** [khanhas/spicetify-cli#1357]
## 📝 Provide a description of the new feature

In your install.sh script you tell us to: 
```
echo "Manually add the directory to your \$HOME/.bash_profile (or similar)"
echo "  export SPICETIFY_INSTALL=\"$spicetify_install\""
echo "  export PATH=\"\$SPICETIFY_INSTALL:\$PATH\""
```

I'm not sure that this is super smart. 
I just restarted my computer and I couldn't get past the login screen. (I use Arch btw ;).
Because the PATH variable was changed, I couldn't get acces to any of my /bin/ programs.
That was where confusing to fix.

**Comment by theRealPadster** [comment]
@afonsojramos I think this is valid. We might want to adjust those instructions. It looks like it's trying to use `$spicetify_install` from the bashrc, which wouldn't exist unless you just ran the script (I think). Up above in the script, we also have the new variables added to the end of the path instead of the beginning. Not sure if that makes a difference or not.

**Comment by ririxidev** [comment]
That's why this script works for some reason. If this person took this from this script, he should use this script to use these export stuff. That's why it exists in first place. $spicetify_install still exists, and should be fine on this script. They probably did something to their PATH and that's why they have probably nothing in it.

**Comment by afonsojramos** [comment]
I'm not sure how this happened, but if this happened to you @Reikimann, maybe you shouldn't use Arch 😂

**Comment by afonsojramos** [comment]
Closing this issue.
