### ISSUE TITLE
Lyrics Plus out of sync after finishing a song

### ISSUE THREAD

**Issue by Anguslam228** [khanhas/spicetify-cli#1360]
## ℹ Computer information

- Spotify version: 1.1.73.517, Mac
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

If I play a song with Lyrics Plus and let it run all the way through, the lyrics for the next song will appear slightly before the song. If I pause, then play again, it re-syncs up and is fine. 

1. Play song
2. Open Lyrics Plus
3. Let the song finish.
4. Next song's lyrics are out of sync (~0.5-1 second faster)

### ✔️ Expected result

Lyrics should be in sync.

### ❌ Actual result

Lyrics for the next song appear too soon.

**Comment by ajiou** [comment]
This problem does not only occur in lyrics plus.
It seems to be an old problem with the interface.

**Comment by zleng1129** [comment]
This is just an actual spotify bug.
Basically when a song plays automatically from a playlist or the queue, the timestamp will be off by about half a second, and lyrics rely on that timestamp to sync up. You can easily correct this delay by quickly pausing/playing, liking the song, hitting the shuffle or loop buttons.
An easy way to fix this issue is if someone just wrote a script that hit the loop button 3 times quickly which is triggered at the first second of every song.
