### ISSUE TITLE
macOS installer is broken

### ISSUE THREAD

**Issue by SupLiCatinG** [khanhas/spicetify-cli#1435]
## ℹ Computer information
Monterey 12.3 Beta 

- Spotify version: 1.1.77
- Spicetify version: 2.8.4

Restarting terminal doesnt work anymore 

I even tried manually downloading install.sh unfortunately no luck for me 

![Bildschirmfoto 2022-01-29 um 12 00 25](https://user-images.githubusercontent.com/94017480/151655005-7ab8f8d2-b068-40ee-af9f-e75c41a526b2.png)

**Comment by ririxidev** [comment]
Give output of install.sh, if you even used it.

**Comment by SupLiCatinG** [comment]
I choose go with homebrew package, works normally now.

**Comment by afonsojramos** [comment]
Do you have a `.zshrc` file under `~`?

**Comment by SupLiCatinG** [comment]
nope but i never had in previous builds

**Comment by SupLiCatinG** [comment]
![image](https://user-images.githubusercontent.com/94017480/151706592-9cc1237d-2952-4b7a-8576-b7c4f500ef9c.png)
i have these only realted to zsh

**Comment by ineedhelp-pls** [comment]
i haven't used spicetify in awhile because i was getting too confused by it but i'm trying to try it out again because i loved when i did have it, so i deleted ALL of the past files that I had of it in hopes that it wouldn't be a problem when i was to reinstall but i'm having the same issue as you (i think) - i thought i had deleted something i wasn't supposed to but if you're getting it too then it must be a bug...or at least i'm hoping it is :'0
![Screen Shot 2022-01-31 at 1 36 52 PM](https://user-images.githubusercontent.com/82544712/151863009-db807b01-dc5f-4cf1-bef4-328681980f58.png)

**Comment by afonsojramos** [comment]
Hopefully, #1445 will fix it.

@ineedhelp-pls @SupLiCatinG can you try the following?
```
curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/install-shell-fix/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/CharlieS1103/spicetify-marketplace/main/install.sh | sh
```

**Comment by theRealPadster** [comment]
Maybe we should create a zshrc if on macos and it doesn't exist?

**Comment by afonsojramos** [comment]
#1445 will do just that @theRealPadster.

**Comment by theRealPadster** [comment]
> #1445 will do just that @theRealPadster.

Doesn't that just check if it exists? Or does it create the file somewhere and I'm just not familiar with the syntax?

**Comment by afonsojramos** [comment]
I suppose the latter 😅 If you run a command with the `>>` it will redirect the output of the command on its left hand side to the end of the file on the right-hand side.

**Comment by theRealPadster** [comment]
> #1445 will do just that @theRealPadster.

Doesn't that just check if it exists? Or does it create the file somewhere and I'm just not familiar with the syntax?

> I suppose the latter 😅 If you run a command with the `>>` it will redirect the output of the command on its left hand side to the end of the file on the right-hand side.

Ah, I didn't realize it created the file if it didn't exist, just that it appends. Nice

**Comment by ineedhelp-pls** [comment]
hi, i followed your instructions and it says that it worked in terminal so yay and i guess my spotify looks a bit different but i can't find any of the spicetify files in my computer (is it because i deleted all of my previous ones?) in order for me to make more changes in the path - sorry if this is a silly question, i've just never coded before so i don't really know what i'm doing lol

**Comment by ririxidev** [comment]
~/.spicetify is the path for spicetify folder

**Comment by ineedhelp-pls** [comment]
it's saying "zsh: permission denied" :(

**Comment by SupLiCatinG** [comment]
Try homebrew build of spicetify, it seems more reliable

**Comment by ririxidev** [comment]
Well, doesn't matter.
@ineedhelp-pls 
`sudo open ~/.spicetify` to open finder in this folder
or `sudo cd ~/.spicetify` to cd in terminal to this folder

**Comment by afonsojramos** [comment]
But it shouldn't be sudo protected, you messed around your permissions somewhere.

**Comment by ineedhelp-pls** [comment]
shoot! If i did, i didn't know that i was doing that - is there a way that i can fix that? the sudo command helped and worked because i located the spicetify file, but now i'm trying to work with the custom apps and i can't find my config even though it said that it generated a "default config-xpui.ini" already so i did the sudo command because i thought that i just couldn't find it but now it's saying that it doesn't exist...and i tried just putting the command into the terminal but it's saying permission denied again :/
![Screen Shot 2022-02-02 at 12 38 34 PM](https://user-images.githubusercontent.com/82544712/152217402-ee255a36-fb26-4b3e-8139-8d7839fe6c63.png)

**Comment by ineedhelp-pls** [comment]
if it's not apparent yet, i really don't know what i'm doing and can use all the help i can get with this :')

**Comment by ririxidev** [comment]
it's in spicetify folder... ~/Default doesn't exist.
