### ISSUE TITLE
Bookmark button gone

### ISSUE THREAD

**Issue by LolaMan** [khanhas/spicetify-cli#144]
The bookmark extension no longer shows up even though it's installed. I used to see the little tag in the corner so I could bookmark tracks but it's not there anymore. The weird thing is the bookmarks I already made still show up but because the button is no longer there I can't make anymore bookmarks.

**Comment by khanhas** [comment]
What is your spicetify version?
Upgradge to 0.9.7 and run `spicetify restore backup apply`

**Comment by LolaMan** [comment]
> 
> 
> What is your spicetify version?
> Upgradge to 0.9.7 and run `spicetify restore backup apply`

This worked. Thank you!

**Comment by DragoCubed** [comment]
I tried running `spicetify restore backup apply` but the bookmark button still won't appear. I don't know what to do :/ I'm on Spicetify 0.9.9 
sorry for being a total noob 😔

**Comment by khanhas** [comment]
@DragoCubed what is your Spotify version?

**Comment by DragoCubed** [comment]
@khanhas thank you so much for replying! I really appreciate it and I for one am swamped with work so I can only imagine how you're doing. 
I'm on Spotify version 1.1.32.618.gda5638a6.

**Comment by khanhas** [comment]
@DragoCubed If you dont mind, try this new version of bookmark extension: https://github.com/khanhas/spicetify-cli/blob/master/Extensions/bookmark.js
Just download this file and put it in user's `Extensions` folder, run `spicetify apply`
You don't need the Custom Apps anymore with this new one.

**Comment by DragoCubed** [comment]
@khanhas I did that but that didn't fix it. Spicetify said that bookmark.js is already in the list. Was it conflicting with the built in one? 

A few seconds after that, I was testing out removing bookmark in the custom app section in the config, there was a Spotify update to v1.1.33.569.gced9e0f5. That's the version I'm on now. The new bookmark.js still won't work and because the custom app isn't enabled it doesn't show up in the sidebar either :/

And now I've just decided to reinstall Spotify and spicetify. I was able to see the the new bookmark extension in action! Honestly prefer the old one (as you can search and sort although that may be added to the new one) but now that everything's all fixed I was able to do that easily. The config looks different too. 

so yeah. reinstalling fixed it. :)
