### ISSUE TITLE
Byte order mark: read (Spotify install path) The handle is invalid

### ISSUE THREAD

**Issue by LWeed1** [khanhas/spicetify-cli#145]
When trying to apply updates to the config file, This message comes up

BOM: read (My Spotify install path) The handle is invalid

**Comment by khanhas** [comment]
Can you give what command you execute and full output?

**Comment by LWeed1** [comment]
PS C:\Users\MyUser> spicetify apply
spicetify v0.9.7
BOM: read C:\Users\MyUser\AppData\Roaming\Spotify: The handle is invalid.
PS C:\Users\MyUser>

**Comment by LWeed1** [comment]
I replaced my name with MyUser

**Comment by khanhas** [comment]
Can you check that if `C:\Users\MyUser\AppData\Roaming\Spotify` exists?

**Comment by thephotoncee** [comment]
i don't know if your issue is already fixed, i have a similar issue as well and here's what i've done 
Open Powershell <admin> 
type the following 

spicetify

For Original Version: spicetify config spotify_path C:\Users\<your user>\AppData\Roaming\Spotify

For Windows Store Version: spicetify config spotify_path C:\Program Files\WindowsApps\SpotifyAB.SpotifyMusic_1.144.538.0_x86__zpdnekdrzrea0

(Windows version of spotify is not recommended for spicetify)

For Original Version: C:\Users\<your user>\AppData\Roaming\Spotify\prefs

For Windows Store Version: C:\Users\<your ser\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs 

spicetify apply or spicetify backup apply

then that should fix the issue just remember to change the <your user> to your username             
![image](https://user-images.githubusercontent.com/73594976/97441407-ac69be80-1963-11eb-9f89-5687bbc230c0.png)

**Comment by AestheticsKSK** [comment]
Thank you so much @thephotoncee it works :) got the prefs path and spotify path mixed up 🥲
