### ISSUE TITLE
Can't detect Spotify "prefs" location. Please manually set "prefs_path" in config

### ISSUE THREAD

**Issue by Nguyenman** [khanhas/spicetify-cli#167]
Yeah, so I'm on the last step, but there's nothing in the appdata/roaming/spotify folder so I'm not sure what I'm supposed to be pointing it to.

**Comment by khanhas** [comment]
You're using Windows Store Spotify. Please uninstall it throughly. Go to Spotify website and download SPotify Installer.

**Comment by xxGregor** [comment]
Yo, 100% sure that im using the app downloaded from spotify website not the Microsoft stroe version and i have the same problem. Trying unistall and install several times and nothing is helping me

**Comment by xxGregor** [comment]
I observe that quick after the instalation of "normal" version Windows is replacing the spotify by "Store" version

**Comment by Nguyenman** [comment]
Yeah, I'm downloading directly from the website. I didn't even know they were on the microsoft store.

**Comment by UpperCenter** [comment]
I can 2nd OP on this one. My issue is on Arch Linux though, no Windows Store here :p

This is a fresh OS install almost, and the same for Spotify and and spicetify  ( Both downloaded from the AUR)
Hopefully the image below can help outline the issue. @ Me if more info is needed.

Thanks
![Issue](https://user-images.githubusercontent.com/46819924/79053335-81708500-7c34-11ea-8374-e192505bf89e.png)

**Comment by arudp** [comment]
This must be happening accross OSs, it seems like a recent update from Spotify broke how Spicetify works.

```
❯ spicetify update 
spicetify v0.9.7
fatal open /Applications/Spotify.app/Contents/Resources/Apps/zlink/css/user.css: no such file or `directory`
```

At least in Mac if you try to look at said path the furthest you can go is to `/Applications/Spotify.app/Contents/Resources/Apps/` where you can see that what I guess used to be a directory (`zlink`) is now a `zlink.spa`.
I tried to create a directory with the structure Spicetify looks for but to no avail, of course, cause Spotify is not looking for that path anymore, I guess.

**Comment by khanhas** [comment]
@UpperCenter Spotify could store its `prefs` file somewhere else, please check all potential config location to see where it is.

@arudp After every single new SPotify update, please run: `spicetify backup apply`
If it's already broken like this, reinstall Spotify to pristine state and run `spicetify backup apply`.

**Comment by jessebett** [comment]
I am getting both this `prefs_path` issue as well as a missing `zlink` directory error on AUR install of spotify on arch.

**Comment by Nguyenman** [comment]
Okay so I found out I was using the windows app but that's only because the Spotify website will ONLY let you download the windows store app. 
I did find the prefs file in: C:\Users\[whatever your user account is]\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\

**Comment by Nguyenman** [comment]
Okay so ignore what I just said. From what I've read, if you've ever installed from the windows store it will always install from the windows store which, imo, is dumb as fuck. Had to install Spotify using a fresh install of windows on a laptop I had lying around, then copied the Spotify folder from:

C:\Users\ *Donor Laptop* \AppData\Roaming\Spotify 
-to- 
C:\Users\ *Main Desktop* \AppData\Roaming\Spotify 

and then only use the exe in that folder. Installing spotify again will erase and convert the entire folder to the windows app version. 

I realize not everyone has a second computer or willing to download 20GB to install a VM, so here's a [mega.nz](https://mega.nz/file/dB8TELxa#P7NHMef3IeK3CxY3sQSnpHbu0JHfdFpgGcgzgIiLAdo) link to download it.

If @khanhas wants me to remove the link I will and just send it to everyone that messages me.

**Comment by Nguyenman** [comment]
Last update:
So even running the spotify.exe in appdata\roaming\spotify, caused the windows store version to install. I finally got desperate enough and manually removed the 30-40 registry files associated with Spotify using CCleaner and I was finally able to install the regular desktop version of Spotify after booting into safe-mode just to be sure the Microsoft store wouldn't meddle with the install.

In case anybody needs help doing this:

1. download, install, and open CCleaner
2. go to registry on the left
3. click Scan for Issues on the bottom
4. untick all the selected files by ticking the box in the top left corner
5. manually go down the long list and remove only the ones with spotify somewhere in the name
6. double check you got them all by right clicking on any of the files> save to text file...> save anywhere you want> open up the txt file in something like notepad++> ctrl+f> type spotify> then press enter/return. If it comes up with nothing, you're done. If not, go back to step 5.

**Comment by jessebett** [comment]
@Nguyenman can you please reopen the issue because you've only addressed it on Windows, but myself @arudp and @UpperCenter are on other OS's.

**Comment by arudp** [comment]
Right! I hit the "like" button as a response but never actually got around to write that the proposed solution worked for me, sorry!

**Comment by jessebett** [comment]
Oh @arudp did that solution work for you? I didn't realize. I don't think it worked for me but I will try again.

**Comment by Nguyenman** [comment]
Hey @jessebett , did it work for you? If not I'll open the issue again.

**Comment by tilktilk5** [comment]
Adding on to this as I am having the same problem. using `yay -Ql spotify` I am able to see where the files are installed but I cannot locate any prefs file. Running Arch here.

**Comment by Jeytas** [comment]
Have you guys tried using `sudo -E spicetify …`? 
Doing that has resolved the issue for me.

**Comment by 3hmoud** [comment]
Hey i am running into this problem and i dont know anything about computer languages but am i correct if i say that "sudo -E spicetify" isnt a command for windows?
Did any win10 users resolve this issue?

**Comment by khanhas** [comment]
@3hmoud No, that's linux command.
What version of Spotify are you using, is it from Windows Store?
Can you remove config file and run spicetify again.

**Comment by 3hmoud** [comment]
reinstalling the config file fixed it! 
ty

**Comment by Shinyhero36** [comment]
I had the same issue on a clean install of spicetify-cli `1.2.1`.
On Windows I replaced field's content:  `prefs_path` from

 - `C:\Users\<yourusername>\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs`
to:
 - `C:\Users\<yourusername>\AppData\Roaming\Spotify\prefs`
 
 And now it's working fine
![image](https://user-images.githubusercontent.com/36128190/109416046-3b432200-79bc-11eb-83a2-5f20a26ed610.png)

**Comment by OmarAmell** [comment]
if u unistall windows store version and install webside version but don't work
-go to C:\Users\{your user}\.spicetify  and open config.ini with a text editor
-change prefs_path to C:\Users\{your user}\AppData\Roaming\Spotify\prefs

**Comment by marchingon12** [comment]
@Shinyhero36 this has nothing to do with the issue but could you tell me the name of your applied theme please? Thank you! :D

**Comment by Shinyhero36** [comment]
Indeed, nothing with the issue :D
There you go
https://github.com/morpheusthewhite/spicetify-themes/tree/master/DribbblishDynamic

**Comment by PrismaPhonic** [comment]
sudo -E spicetify apply seems to get past this error, but now my Spotify won't render anything visual whatsoever when I try to start it, regardless of which theme I'm trying to use.

**Comment by rayjay8** [comment]
> sudo -E spicetify

fucking legend!

**Comment by SaltNuggets** [comment]
Hello, I struggled this issue for quite a while on mac, the fix is easy enough for me, all I needed to do was change the prefs file path from using ~ to the full path.

**Comment by kingofmortals** [comment]
At first installation everything worked fine (note: the spicetify was working on windows store application. As the path spotiy.AB is of windows store not of a web download. ) so I tried to use the ad-blocker but it showed it needed spotify application from the web. so I dumbly unistalled the windows version and installed the web version. so, after that spicetify showing the path is not specified and after making the path change it started showing reinstall spotiy. it cant back up now.

**Comment by khanhas** [comment]
@kingofmortals Run `spicetify -c` to get config file path, remove config file, reinstall spotify and try again. Also adblocked version is not support, please don't ask further.

**Comment by alessiocelentano** [comment]
Once you created your config, run `spicetify apply`.
- **Error 1** - `You haven't backed up. Run "spicetify backup apply".`
Cool. Just run the command, you should have no problems if it will print `Everything is ready, you can start applying now!`
- **Error 2** - `open /path/to/a/spotify/config/file: permission denied`
When you see `permission denied` for many people it's natural to run the command with `sudo`. Well, this will generate another **error**.
  - **Error 2.1** - `Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini`
Your `prefs_path` is not necessarily wrong (check it out anyway), this error is due to `sudo`. This is not the right approach.
- **Solution**: So, in order to fix that, you have to `chmod` the `/path/to/spotify` (i.e. `/opt/spotify`, `/usr/share/spotify`), you can find yours in the **error 2** path.
`sudo chmod -R 777 /path/to/spotify`
and
`spicetify apply`
- **Other errors**: when you run `spicetify backup apply` you could get some permission denied, just use the `chmod` as in the **solution**. If you messed up something and get other errors, reinstall Spotify  and delete the config (run `spicetify -c` for the path).

**Comment by OlaoluwaM** [comment]
I installed spotify via flathub and my `prefs` path is empty

**Comment by OlaoluwaM** [comment]
For flatpak users running into the `prefs_path` issue. Check this https://github.com/flatpak/flatpak/issues/1214#issuecomment-347752940

**Comment by MarcusVH98** [comment]
For those still struggling on Linux; there's documentation on the install page with fixes. Worked for me using AUR version. https://spicetify.app/docs/getting-started/installation#note-for-linux-users

**Comment by NutBanana** [comment]
I managed to solved this problem somehow
the issue was that the "pref" file wasn't where the the program was looking for it,
so using "open file location" from spotify i found the "pref" file in the user folder
copied it
and created a chain of folders as the ones requested by the program in spotify's location on C: and in the last one paste the copied "pref" file
i know it might sound crude but it worked for me

**Comment by remon06** [comment]
@NutBanana Thanks Man It worked.<3

**Comment by Josephfnx** [comment]
@NutBanana where did you create the folders?

**Comment by Ronald123ol** [comment]
In my case (windows), I had installed the Microsoft Store version and I had installed spicetifi when I got the message that I must have installed the version from the official website, not the microsoft version.  What I did was to uninstall the microsoft version and install spotify from their website. Then I got the error mentioned in this topic. If this was also similar to what happened to you, I recommend the following solution:

**1.** (**Config-xpui.ini**). Go to` C:\Users\<YourUserName>\AppData\Roaming\spicetify`. And open with visual studio code: config.xpui.ini

**2.** Change the default path of **"spotify_path"** to the path where you have installed spotify (it can be: 
`C:\Users\<YourUserName>\AppData\DataRoaming\Spotify`). This path marked between parenthesis is the one that you must place in where it says "spotify_path" replacing it by the one that has by default. 

**3.** Change the default path from "prefs_path" to the path where you have the **"pref"** file (it can be:
 `C:\Users\<YourUserName>\AppData\DataRoaming\Spotify\pref`). Where pref is a file.  Then save the changes. 

**4.** Go to powershell and type "`spicetify apply`".  Without the quotes and it should work correctly.


_**Concept:**_ Basically, I replaced the path "spotify_path" to the path where I have installed the spotify I downloaded from the web, because the default was the path where I had installed the spotify from microsoft store. And the same happened with "prefs_path".

**Comment by Lmorthian** [comment]
For some reason i cant seem to find my prefs file.

**Comment by IraLeeBell** [comment]
For anyone running Linux who is encountering the issue where Spicetify can't find your config file, please ensure that you have run Spotify and logged in after you've installed it. I was encountering the same issue, but it was because I was doing a clean build of Linux (Ubuntu) and though I had installed Spotify, I hadn't yet opened it and logged in. Once logged in, then run:

`spicetify config current_theme Dracula`

then run:

`spicetify backup apply`

**Comment by Xaypanya** [comment]
> I managed to solved this problem somehow the issue was that the "pref" file wasn't where the the program was looking for it, so using "open file location" from spotify i found the "pref" file in the user folder copied it and created a chain of folders as the ones requested by the program in spotify's location on C: and in the last one paste the copied "pref" file i know it might sound crude but it worked for me

not every hero wears a cape. thanks man

**Comment by FoxDavoid** [comment]
In my case, as a Linux user, the solution was to log in before trying to install Spicetify. There is no prefs files when there's no account inside.
