### ISSUE TITLE
Spicetify uses incorrect command to launch the Spotify flatpak

### ISSUE THREAD

**Issue by Addisonbean** [khanhas/spicetify-cli#194]
I used to be able to listen to local files in Spotify, but after starting to use spicetify I get the message "Spotify can't play this right now. If you have the file on your computer you can import it." I am attempting to play the song from the "Local Files" section on Spotify, so Spotify is definitely finding the file.

Spicetify: 0.9.9
Spotify: 1.1.10.546.ge08ef575
Ubuntu: 20.04

**Comment by khanhas** [comment]
I'm not sure why not able to play Local files has anything to do with Spicetify since it doesn't touch any binaries file.
Can you run `spicetify restore` then try playing Local file to see if it still works?
Also, you spotify version is ancient, try upgrading if you can.

**Comment by Addisonbean** [comment]
Ok so I tried doing `spicetify restore` and it still isn't working... I also tried updating to 1.1.26 and it's still not working. I think it must have to do with switching from the snap app to the deb version.

**Comment by Addisonbean** [comment]
Installing the flatpak version of spotify fixed it!

However local files only work when running it with the flatpak command `flatpak run com.spotify.Client`. When using spicetify to open spotify, it uses the path to the spotify binary to launch it which breaks the flatpak's ability to play local files for some reason. Although I can work around this by just relaunching spotify with the right command, it'd be nice to have spicetify launch it correctly since I've been making lots of edits to themes.

**Comment by khanhas** [comment]
I honestly don't want to deal with Flatpak and their isolating system entirely.
But it's a easy hack that you could just launch command you need to open Spotify correctly **after** a spicetify operation with `--no-restart` flag:
```
spicetify apply -n && killall -q spotify && your_command_to_launch_spotify
```
I suggest this because I'm experimenting `flatpak` with Windows Subsystem Linux, I need to add some extra flags (setting DISPLAY environment variable) to successfully launch it. So I guess there is no optimal solution for everyone, just hack your way to it.

**Comment by khanhas** [comment]
I just saw you mentioned about enable devtool. You only need to run `enable-devtool` once.

**Comment by Addisonbean** [comment]
Ahh, ok. Thanks for the help!
