### ISSUE TITLE
newRelease Feature Suggestion

### ISSUE THREAD

**Issue by afonsojramos** [khanhas/spicetify-cli#247]
What do you think of an addition of a type of release identifier to `newRelease.js`?

Personally, I would like to know whether or not it's a single or an album, without having to click on the release.

**Comment by khanhas** [comment]
This is very nice idea and it will be added in next patch.

Unfortunately, type of release would not be entirely correct since new release API does not return type of release:
```json
{
    "uri": "spotify:album:3q64RsuH40agLneJfSrZzs",
    "name": "Paralyzed",
    "cover": {
        "uri": "https://i.scdn.co/image/ab67616d00001e025b9d514cdc8dd31446971b4e"
    },
    "year": 2020,
    "track_count": 1,
    "month": 7,
    "day": 17
}
```
Regardless release is Album, EP or Single, they're always organized in `album` uri scheme. And to get album type information, we have to make another request to album detail API for each of new releases. This alone adds huge amount of delay to our extension, which already work a bit slow.

My solution is just deduce type from `track_count`, 1 is Single, >1 is Album. I hope it would suffice most of use cases.

**Comment by afonsojramos** [comment]
So far I actually have had a great experience with it, even while using the Dribbblish theme (which I believe to be the most complex).

Either way, the track count does seem to be a nice idea to not oversaturate with API requests, however, the number of tracks in an album is rarely under 7.

Wikipedia even states the following for an EP: "a modern EP is usually defined as generally between four and six tracks".

As such, how about:

- `track_count` =< 3 -> `single` (to encapsulate releases with mixes of the single and such)
- `track_count` > 3 &&  `track_count` =< 6 -> `EP`
- `track_count` > 6 -> `Album`

What do you think?

**Comment by khanhas** [comment]
I think it's great. Thank you!

**Comment by khanhas** [comment]
So the update on extension is pushed. You can download the file and put in your `~\.spicetify\Extensions` folder, then run `spicetify update -e`.

**Comment by afonsojramos** [comment]
Looking real good! Thanks!
