### ISSUE TITLE
feature request: pop-out mini player

### ISSUE THREAD

**Issue by hoshsadiq** [khanhas/spicetify-cli#255]
Hello, I've been looking for a good pop-out mini player for spotify but have yet to be able to find one. Seems this might be the right place to ask for one. The `fullAppDisplay.js` extension comes close but it's not the same. I'd like to keep the main window in a separate workspace, and then have a pop-out player that is in the main workspace.

**Comment by khanhas** [comment]
It's not possible to launch another browser window.
You might want to look into Rainmeter widget.

**Comment by hoshsadiq** [comment]
I'm a Linux user so rainmeter isn't an option. Is it perhaps possible to make the full App Display extension act more like a pop-out player? E.g. when activating it, make Spotify smaller (and vice versa) and other similar things?

**Comment by khanhas** [comment]
Sorry, I cracked my head out but couldn't think of any solution. At least it's not easy.
Since you are using Linux, browser window doesn't have dimension constraint as in Windows and you can resize it as small as you like. But there is no API endpoint from browser layer to tell native layer to change window size so it's not scriptable (activate on demand).
On the other hand, it is possible to write shell script (python/node) to resize Spotify window but it's hard to activate full app display mode from script. It's hard because the only mean of communication I know is WebSocket. You need to setup Websocket server from your script and setup Spotify Websocket client to receive message/command from outside.
