### ISSUE TITLE
Add more vim bindings to keyboardShortcut.js

### ISSUE THREAD

**Issue by rien333** [khanhas/spicetify-cli#27]
The keybindings extension rocks! Excellent way to incoperate spotify into my more keyboard focused workflow (which could be a reason to bring more such nerds to this app).

It would be great if `keyboardShortcut.js` provided even more vim shortcuts, though. I especially miss a way to go back one page, and to some extent I want to be able to go the top/bottom of the page. I propose modeling these shortcuts based on [qutebrowser](https://github.com/qutebrowser/qutebrowser), a  vim-inspired web browser.  So going forward/backward would be `shift+h/l`, jumping to the bottom/top would be `g/G`. For consistency, follow should be `f` (see also zathura, the vim inspired pdf reader) instead of what it is now. Maybe `/` for focusing the search bar as well? 

 My javascript is sort of eh so I won't be able to do it myself, at least not until some later time.

**Comment by rien333** [comment]
Looking at the source file, there already seems to be some code to implement e.g. going backward/foward (sorry for missing this). Given the probably somewhat nerdy following, it might be a good idea to make it consistently follow vim bindings, though.

**Comment by khanhas** [comment]
I'm glad you like it!
Your suggestions are reasonable, I should comply with keyboard-driven softwares out there instead of inventing my own keybinds.

I did make a few changes here: https://github.com/khanhas/spicetify-cli/blob/7f8205a50d69166bf865547e7a4ccbb277766f5a/Extensions/keyboardShortcut.js

If you have time, please test it out. 

I added `G/Shift+G` scroll top/bottom, `/` to search, changed navigating forward/backward to `shift+H/L`, activate follow link function to `F` and added some documentation for users who want to change or add their own keybinds.

If you think of any more feature that are suitable for Spotify client, please do tell me.

**Comment by khanhas** [comment]
To install that, run:
```bash
curl https://raw.githubusercontent.com/khanhas/spicetify-cli/7f8205a50d69166bf865547e7a4ccbb277766f5a/Extensions/keyboardShortcut.js -o "$(dirname "$(spicetify -c)")/Extensions/keyboardShortcut.js"
spicetify apply
```

**Comment by rien333** [comment]
Works great, tysm! It's a little difficult to get search bar to unfocus with the keyboard though, say when I want to select one of the search results.  Not really sure if anything can be done about that, though. Intuitively, I think `ESC` would fit this purpose, but that might problematic. A modifier key + `/` might be a better way to unfocus.

**Comment by rien333** [comment]
I'm not a vim user actually - but all my main apps have vim shortcuts - so I don't have a ton of ideas about making spotify even more vim like. The most intuitive way to unfocus textfields with the keyboard still seems `ESC` to me, which currently just clears the text in the bar. Be sure to make a pull request/post in this thread if you have spotify keyboard experience improvements!

**Comment by khanhas** [comment]
Feel free to pitch your ideas here. I will help you on developing keystroke callbacks if I can.

**Comment by dereknelson** [comment]
@khanhas I think we should come up with a keybind to blur focus on the search field, because having to use a mouse for **anything** kinda ruins the point of using the keybinds in the first place. 

first thing I'm most interested in is being able to queue from hitting "f". I have two ideas: 
1. a keybind to "right click" and open the context menu modal, and parse that for links: 
![image](https://user-images.githubusercontent.com/6868432/63958566-9a874580-ca58-11e9-83fe-8007be442013.png)
2. prepending q to a link result, so it would look like this: 
![image](https://user-images.githubusercontent.com/6868432/63958456-5d22b800-ca58-11e9-8b61-dbe1c0ef398a.png)
I noticed you exposed queue song which is how the 2nd one would work, all we'd have to do is get the URI somehow.

**Comment by AtomToast** [comment]
I have a few comments on the vim shortcuts:  
first of all big <3 been looking for these for spotify for ever.

Next I have some issues with the shortcuts:  
- cancelling the vim selection mode with f does not work once you entered one character. Eg multiple selections start with q > once you press q you can abort with esc anymore.
- the slash shortcut for searching does not appear to work on german keyboards. For testing purposes I changed my system keyboard to US american and then the respective shortcut worked though.  
My OS is Manjaro Linux  

I also have some suggestions for new shortcuts:
- some way to scroll a full/half page. In vim you can do this with ctrl+f/b and ctrl+d/u respectively. Maybe here something like shift+j/k would be more convenient?
- a way to scroll through songs individually. I'm not sure if there is a way to select a song with a shortcut but if you select one with a mouse you can move up and down with the arrow keys. However as a vim user I hate using the arrow keys and having to click on a song kind of defeats the purpose of using shortcuts
- in a similar vein when having selected a song I'd like to be able to execute actions on it like playing or opening the context menu. currently this works with enter and the menu key but vim keys would be nicer. This one wouldn't be a priority though
- Last but not least it would be nice when being able to select songs to jump around the view with the vim keys H,M and L to jump to the High-Mid-Low position of the view. However this would currently conflict with other shortcuts so something else might need to be chosen

**Comment by rien333** [comment]
Another good binding idea: seeking in tracks with `,` (backward) and `.` (forward), much like mpv and cmus.

**Comment by rien333** [comment]
That said, @khanhas, how do you bind the period key (i.e. <kbd> . </kbd>)?  I tried `DECIMAL_POINT` from `keyboardshortcut.js`, but that didn't work.

**Comment by khanhas** [comment]
@rien333 It's `190`
You can get other keycode from this website: https://keycode.info/

**Comment by khanhas** [comment]
Also, I found no time to implement any of suggestions.
You guys are always welcomed to make a pull request, I will take a look, improve or bug fix if it's needed.
