### ISSUE TITLE
Error when applying theme (read-only file system)

### ISSUE THREAD

**Issue by lukefly2** [khanhas/spicetify-cli#3]
Running **spicetify apply** gives the following error:
fatal remove /snap/spotify/current/usr/share/spotify/Apps/about.spa: read-only file system

I'm using Ubuntu 18.10.

**Comment by khanhas** [comment]
As I mentioned in 0.4.1 release note, I don't know any workaround mount system. Really need some help from linux gurus.
The idea is un-mount the snap file or mount point which is in read-only state then mount it again with read-write flag:
```bash
mount | grep spotify
```
![screenshot from 2019-01-04 10-18-07](https://user-images.githubusercontent.com/26436809/50672343-133d1b80-100a-11e9-92b4-1ee27d203c44.png)

```bash
sudo umount /snap/spotify/28
sudo mount --rw /var/lib/snapd/snaps/spotify_28.snap /snap/spotify/28/
```

But it's still in read-state:
![screenshot from 2019-01-04 10-38-45](https://user-images.githubusercontent.com/26436809/50672836-f2c29080-100c-11e9-8ab1-ee2486021843.png)

**Comment by lukefly2** [comment]
Thanks for the quick reply! I love your project and I hope this gets fixed soon.

**Comment by khanhas** [comment]
Seems like it's [impossible](https://askubuntu.com/a/1034548) to defeat snap. 
But fortunately, you can install directly from Spotify repository. Following these steps:
1. Uninstall Spotify in Snap or run command `snap remove spotify`
2. Remove .spicetify folder: `rm -r ~/.spicetify`
3. Open http://repository.spotify.com/pool/non-free/s/spotify-client/
You can see there are 2 deb files, for i386 and amd64. You should pick amd64 if your Ubuntu is 64bit version because seems like they stopped upgrading the client for i386.
4. Install deb file you just downloaded with Ubuntu Software. Might take a bit.
5. After it's installed successfully, run command:
```bash
sudo chmod 777 /usr/share/spotify -R
```
to take files ownership and gain write permission.
6. Backup and apply Spicetify
```bash
spicetify backup apply
```
7. Enjoy!

![screenshot from 2019-01-05 10-31-10](https://user-images.githubusercontent.com/26436809/50719847-15b87780-10d5-11e9-95f6-3209ded70220.png)

**Comment by lukefly2** [comment]
Thanks for the help! Closed as fixed.
