### ISSUE TITLE
error: Cannot backup app files

### ISSUE THREAD

**Issue by Const4ntin3** [khanhas/spicetify-cli#334]
Hi,
I tried to apply spicetify v1.1.0 on my windows machine (with the lastest updates)
I downloaded the newest spicetify version, unzipped it, run the execution file, opened powershell and run

"PS C:\Users\'username'\OneDrive\Desktop\spicetify-1.1.0-windows-x64> spicetify backup apply
spicetify v1.1.0
Backing up app files:
error Cannot backup app files. Reinstall Spotify and try again."

As requested I uninstalled spotify, downloaded the installer from the spotify website and tried spicetify .
Still got the same error message.
Also tried to restart the machine and nothing changed.

**Comment by khanhas** [comment]
Please don't run spicetify from OneDrive folder. That's is the reason why it doesn't work properly, spicetify does not have right to write in OneDrive folder.

**Comment by datnotguy17** [comment]
This issue had been bugging me for a while, and I couldn't figure out for the life of me how to fix it. But I think I may have found the solution.

If you're getting this issue, when you search up "spotify" in the windows search your spotify likely looks lime green with a thick, square border around it. This is the Windows App version of Spotify. This also means that you and apps cannot change anything inside of the app. Fear not, here's how to change your directory (also just a quick revision, I believe that the issue here is that the app is looking in the wrong directory too, but were gonna fix that.)

Open Spotify and open up Task Manager.

Click on the dropdown for Spotify, this will bring up like 4 other icons.

Right click any one of them and hit "Open File Location"

This will bring you to the Spotify folder inside of the Windows Apps folder, one that is usually restricted.

Now, just copy the path to the Spotify folder, and change the directory inside of the config,ini for Spicetify

Hope this helps :)

**Comment by KIvanRuiz** [comment]
Another possibility is the **spotify folder being set to read only**, do the same method to get to the spotify folder, go to its properties tab and uncheck "read only", after that apply spicetify
