### ISSUE TITLE
Cant access settings (ctrl + p, button)

### ISSUE THREAD

**Issue by OhItsTom** [khanhas/spicetify-cli#440]
Hi, recently i havnt been able to access settings.

This never used to be an issue, when spicetify isnt applied and its a fresh install of spotify i can access it perfectly but the second i apply a theme/ect i cant seem to access them anymore it just stays on a loading cog, and sometimes there isnt even a loading cog at all.

I use DribbblishDynamic if thats any help

**Comment by OhItsTom** [comment]
My spicetify version is 1.1.0

**Comment by khanhas** [comment]
Look into Console and see if there is any error.

**Comment by OhItsTom** [comment]
how do i open the console

**Comment by khanhas** [comment]
```
spicetify enable-devtool
```
then in Spotify, hit Ctrl Shift i

**Comment by OhItsTom** [comment]
![image](https://user-images.githubusercontent.com/22730962/110211613-51a31f00-7e8f-11eb-8035-6c949caf1c01.png)
![image](https://user-images.githubusercontent.com/22730962/110211615-54057900-7e8f-11eb-854c-9223e2bcac35.png)

**Comment by SetuCoder** [comment]
How do I fix this? I just wanna disable Spotify on startup. I'm on a mac so I cannot do it from Task Manager nor System Preferences as Spotify isn't showing up there. They closed my issue saying it's duplicate but here there is no solution on how. Please fix this up or tell me a solution.

**Comment by OhItsTom** [comment]
not an issue with spicetify.

**Comment by SetuCoder** [comment]
But when I uninstalled spicetify and reinstalled just the Spotify app, the settings page opened. I guess there is some issue with Dribbblish Themes, the original opener of this issue also uses Dribbblish Theme, as mentioned above.

**Comment by OhItsTom** [comment]
Ah so you can get into settings without dribbblish? Must be something wrong with how spotify loads shit in the new update or it changed variable names on some stuff, we'll just have to wait for a dribbblish update ig

**Comment by ayush729p** [comment]
@OhItsTom did you find a fix? plagued and frustrated by the same problem as well. Using Dribblish Dynamic with Spicetify 1.2.1.

**Comment by ayush729p** [comment]
@OhItsTom @SetuCoder I found a fix! it's similar to the one in #336 but in this case `spicetify restore` won't work.
Step by step guide how to fix it:
1.  Uninstall Spotify (with the corrupted settings page). You don't need to uninstall spicetify. Though you could upgrade it to v1.2.1 but you still have to go through this fix.
2. Now reinstall Spotify, but don't spice it up just yet! Do login and check settings page is working correctly. Now close Spotify (preferably from task manager).
3. Hit Win+R, if on windows (idk the file locations on any other OS) and type %AppData%\Spotify\Apps (or) navigate from file explorer to C:\Users\<your_user_account>\AppData\Roaming\Spotify (Keep hidden files/folders visible in file explorer).
4. Now in this apps folder backup settings.spa to a safe place. I copied it to documents but you can keep on Desktop.
5. Now spice Spotify up! (run `spicetify apply` in cmd/powershell). If Spotify opens up, close it again like in step 2.
6. Go to the same location as step 3. Instead of .spa files you'll now have their corresponding folders instead. Like there will be a settings folder instead of settings.spa.
7. Open your backed up settings.spa in a files archiving software like WinZip, 7zip, etc. Copy the files inside it and paste them in settings folder mentioned in step 7.
8. Open Spotify now! Hopefully the settings page (Ctrl+P) is fixed.

Here's a screenshot after the fix:
The dribblish customization on this particular page is gone so the text colors are the default but at least the page is still usable!
![image](https://user-images.githubusercontent.com/71623044/112261504-057b1b80-8c92-11eb-80b1-715fb341767e.png)

@khanhas Please look into this if it's an caused by spicetify-cli or the spicetify-themes. People with other themes are also unable to access settings like in #441 .
