### ISSUE TITLE
Black Screen after installing Spicetify

### ISSUE THREAD

**Issue by BurgOwO** [khanhas/spicetify-cli#459]
Hi, I'm using Ubuntu with KDE and I recently tried installing Spicetify, but as soon as I applied the theme the whole app turned black. I installed it with the binary, not through snap or some store, but it isn't working. Maby I am doing something wrong since I am a noob with Linux, can someone help me? Thanks a lot.

![image](https://user-images.githubusercontent.com/23221350/111518235-2a353780-8756-11eb-8e5e-78b7eec0e61d.png)

P.S.: I had to manually set the prefs location and also if I use the command "spicetify" it doesn't work, but it works if use "/root/spicetify-cli/spicetify"

**Comment by khanhas** [comment]
1. How did you install Spotify?
2. About spicetify path, it's Linux basic. Learn about $PATH.

**Comment by BurgOwO** [comment]
> 
> 
>     1. How did you install Spotify?

1. I installed is using the following commands:
`curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add - `
`echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list`
`sudo apt-get update && sudo apt-get install spotify-client`
These are the commands that I have found on the Spotify website, then to install Spicetify I used:
`curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh`

> 
>     2. About spicetify path, it's Linux basic. Learn about $PATH.
2. Ok, thanks a lot, sorry if this is basic, I am pretty new to linux

**Comment by Mr-istov** [comment]
Hello @BurgOwO
Welcome to Linux and the open source community :smile:
From what I can guess, I think you are missing permissions on the `spotify` folder. Since you said you are on Ubuntu, I think `spotify` should be installed under `/usr/share/spotify`. Can you try re-installing `spotify`, removing the left-overs from `spicetify` and `spotify` if there are any, installing `spotify` again and before running `spicetify` adding permissions.

1. Uninstall spotify: `sudo apt-get remove spotify`
2. Remove the left-overs: `sudo rm -rfv /usr/share/spotify/` and `sudo rm -rfv ~/.config/spicetify/`
3. Install spotify again, this time you don't have to run all the commands from your comment, just run this: `sudo apt-get install spotify-client`
4. Run the following commands for adding permissions on the `spotify` folder: 
```
sudo chmod a+wr /usr/share/spotify
sudo chmod a+wr /usr/share/spotify/Apps -R
```
5. Run spicetify and apply your theme. 

Hope this resolves your issue. If you encounter any issue during running some of the above steps, happy to help you out.
