### ISSUE TITLE
When I close Spotify with a theme, and when I reopen it, the theme is gone

### ISSUE THREAD

**Issue by AlexTheKing14** [khanhas/spicetify-cli#518]
Hello, when I close Spotify with a theme, and I reopen Spotify, the theme is gone...

**Comment by Pixouls** [comment]
two things: 
it's recommended to get a shortcut that runs spicetify auto apply and use that again so that every time you open it the theme will apply. i haven't figure out how to do that though.
https://github.com/khanhas/spicetify-cli/wiki/FAQ (see the section section)

the second thing is that i noticed that you had a pref error originally. most of the threads talk about having a pref folder and it being seen as invalid or because they had the windows store version. it was working for me but i did a reinstall of spotify today and now spicetify does not work for me, i definitely do not have the window's store version. so basically, how did you fix your file error?

**Comment by Pixouls** [comment]
okay i found a response here from the developer in the past about how to make a shortcut that runs spotify automatically https://spectrum.chat/spicetify/general/is-there-a-way-to-automatically-inject-spicetify-when-spotify-launches~27a695f3-7f1b-4b82-a447-9f516143ac2e
