### ISSUE TITLE
error-dialog.generic.header

### ISSUE THREAD

**Issue by arysia** [khanhas/spicetify-cli#546]
Whenever I try to apply a spicetify theme, this is what happens to spotify

![2021-04-29-182957_1127x694_scrot](https://user-images.githubusercontent.com/35059319/116637566-16feb580-a919-11eb-8f85-6f131494854a.png)

I've tried reinstalling spotify/running `spicetify backup apply`. OS is Ubuntu 20.04

**Comment by khanhas** [comment]
Upgrade spicetify to latest. Reinstall Spotify and try `spicetify backup apply` again.

**Comment by arysia** [comment]
1thank you

**Comment by befabry** [comment]
Hello,

This issue seems to have resuscitated in 2023.

OS : Arch
Spotify version : extra/spotify-launcher 0.5.1-2
Spicetify : 2.24.2

Fresh install of Spotify and used the aforementioned command. 

![image](https://github.com/spicetify/spicetify-cli/assets/17452648/9cbddc2e-b7a0-4917-a285-242db1f09f94)
