### ISSUE TITLE
Re-implementation of Apps system on 2.x

### ISSUE THREAD

**Issue by itsmeow** [khanhas/spicetify-cli#563]
I see you've cut out the Apps system for the new XPUI, I was wondering if it's still possible in the new UI or if Spotify also removed the functionality? Will an alternative to https://github.com/khanhas/genius-spicetify/ be possible if so?

Maybe it could be rewritten as an extension if so?
Awesome work on getting the project running on the new UI so quickly.

**Comment by khanhas** [comment]
I got some work done on custom apps injection.
But apps need to be built from the ground up because we can't use Spotify assets anymore. So i don't know. It's impossible to port anything anymore.
Spicetify APIs are still available in app environment tho. And app has to be written with React JS components and returns a React object.
```js
const react = Spicetify.React();
const span = react.createElement(
    "span", 
    { style: { 
        color: color,
        border: "3px",
    } },
    "inside app"
);

function render() { 
	return react.createElement("div", {}, span);
}
```

**Comment by itsmeow** [comment]
New apps look good. Using React is great.
