### ISSUE TITLE
System cannot find the path specified

### ISSUE THREAD

**Issue by crawmptastic** [khanhas/spicetify-cli#570]
Hello, so glad spicetify has been working strong with the new spotify update.

I had everything working yesterday (after installing new spicetify version) but after turning my computer on today now I get this error 

31mfatal[0m open C:\Users\*NAME*\AppData\Roaming\Spotify\Apps\zlink\css\user.css: The system cannot find the path specified.

Please me know how I can fix this, already tried reinstalling spicetify again, no luck.

**Comment by Hexlicious** [comment]
Remove spotify again but after installing it (before applying spicetify) insert the code below in your powershell.

```
rm "$env:localappdata\Spotify\Update"
mkdir "$env:localappdata\Spotify\Update"
icacls "$env:localappdata\Spotify\Update" /deny "$env:username":D
icacls "$env:localappdata\Spotify\Update" /deny "$env:username":R
```

This will stop spotify from force updating to the latest version, which seems to break spicetify due to some structure changes from what I've managed to gather, it worked wonders for me.

**Comment by crawmptastic** [comment]
That seemed to do the trick! Thank you!
