### ISSUE TITLE
spicetify folder under windows

### ISSUE THREAD

**Issue by JulienMaille** [khanhas/spicetify-cli#592]
Could you clarify why `spicetify -c` returns `${HOME}\.spicetify` while install.ps1 downloads stuff to `${HOME}\spicetify-cli`?

**Comment by khanhas** [comment]
`spicetify -c` returns config file location and user's other assets (personal folder). It's in different location than spicetify binary because it's suppose to be reliable across system installation. You can just backup `.spicetify` when you reinstall your OS. Also, install spicetify using install script will overwrite everything in install location, hence any local modification on default theme and extensions will be lost. It's better to store your works in your personal folder and keep your peace of mind.
