### ISSUE TITLE
Search in bar is broken after the latest update

### ISSUE THREAD

**Issue by ATiltedTree** [khanhas/spicetify-cli#71]
After I updated spicetify, backed up and applied again, the search page now looks like this:

![image](https://user-images.githubusercontent.com/47182955/64926781-d0bb1800-d801-11e9-9e0a-1f0f164549bd.png)

I restored, cleaned and apply many times, even with different themes, but this issue keeps happening.

**Comment by khanhas** [comment]
Search in Bar is still experimental feature by Spotify. They have 2 variables for it in the code: `SearchInSidebar` and `FusionSearch`.  
In version 1.1.15, they kinda finished it and only used `FusionSearch` instead of `SearchInSidebar` as before. I'm keen to support more newer client version than the old one. So you have 2 options:
- Wait for new Spotify client update for Linux. It might not takes long. 
- Use old spicetify version.

**Comment by ATiltedTree** [comment]
They do not have that version for spotify on their official snap. They are still on 1.1.10. I guess I will just deaktivate the feature, untill they update the linux client.

**Comment by khanhas** [comment]
Woo. How do you make Spicetify to work with Spotify from Snap btw?

**Comment by ATiltedTree** [comment]
I do not use the snap. I just used it as an example for the current version on linux. They are on the same version with their [deb packages](https://repository-origin.spotify.com/pool/non-free/s/spotify-client/) as well. Spicetify would not work with snaps because they are on squashfs filesystems and just mounted as a directory which makes them not writable at all.
