### ISSUE TITLE
A Spotify Canvas feature

### ISSUE THREAD

**Issue by theman122** [khanhas/spicetify-cli#886]
I don't know if this can be done or if it's already been done/requested, but Spotify Canvas on Spicetify or Spotify would be awesome to have. I love having them play when I listen to music on my phone so I'd love it on my computer. I'd imagine it'd play when the music is fullscreened or replace the small cover of the song while it's playing, but I'd understand if it couldn't work because of the portrait resolutions of most Canvas videos.

**Comment by itsmeow** [comment]
https://github.com/itsmeow/Spicetify-Canvas

**Comment by itsmeow** [comment]
I will note that it wouldn't really be plausible for this to be implemented into the client regularly as a default extension, because it requires modifying Spotify's build of Chromium Embedded Framework to enable H264/mp4 support, as that is the only format Canvases are served to the mobile client with.

CEF by default excludes proprietary codecs, and it's not legal to distribute builds with them, so you have to build it yourself. The extension part of obtaining and adding Canvases is relatively straightforward, but requires some Protobuf trickery. You can't use the included JS APIs to send the data, since they all accept JSON inputs, not binary data.
