### ISSUE TITLE
Spicetify update produces fatal error

### ISSUE THREAD

**Issue by agandra** [khanhas/spicetify-cli#9]
Running spicetify update produces:

spicetify v0.6.0
fatal open /Applications/Spotify.app/Contents/Resources/Apps/zlink/css/user.css: no such file or directory

All previous steps were successfully completed using homebrew on OSX.  spicetify_data folder only has Backup, Extracted, and config.ini in it.  No themes folder, am I supposed to manually add?

**Comment by jcruzs** [comment]
When you update the app the internal css disappear. What I did was run in the terminal: 

spicetify apply

Terminal ask me to run 'spicetify restore...' as a way to restore the css. For the themes and apps, you need to add it manually from the clone repo. After making the modifications for theme, apps, color otr other items, do not run spicetify update as appear in the guide because it will only update color but not apps or extensions. Due to this, better run 

spicetify apply

After running this command, everything works fantastic.

**Comment by LightZxZ** [comment]
how do i fix this? unlinkat /usr/share/spotify/Apps/xpui.spa: permission denied i got spotify from the official web site on linux and when i try to apply spicetify it doesnt work please help me!

**Comment by rizkhal** [comment]
Hy @LightZxZ, do you have any solution?

**Comment by gospodzverina** [comment]
try "sudo chmod a+wr /usr/share/spotify/Apps/". It worked for me :,)
