### ISSUE TITLE
Cannot use Invoke-WebRequest on IE-disabled Windows machines

### ISSUE THREAD

**Issue by danielphan2003** [khanhas/spicetify-cli#96]
The following error shown up after I had ran the installation script for Windows:
```
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. 
```

I have disabled IE on my machine. Please consider using 
```
(new-object net.webclient).DownloadString()
``` 
instead for compatibility across IE-enabled and IE-disabled machines

**Comment by LivingWithHippos** [comment]
I had this problem too, opened PR #97 to fix it, I used the parameter specified in the error instead of (new-object net.webclient).DownloadString(). 
If accepted you'd also need to update the line at https://github.com/khanhas/spicetify-cli/wiki/Installation#windows-pre-built from 
`Invoke-WebRequest "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression`
to
`Invoke-WebRequest "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" -UseBasicParsing | Invoke-Expression`

**Comment by danielphan2003** [comment]
Thanks! It's working properly now. I will close this issue as the PR #97 has already been merged.
