### ISSUE TITLE
Cant Apply Dribblish or any other theme

### ISSUE THREAD

**Issue by prango71** [khanhas/spicetify-cli#987]
## ℹ Computer information

- Spotify version: 1.1.66.580.gbd43cbc9
- Spicetify version: 1.1.0

## 📝 Provide detailed reproduction steps (if any)

While applying spicetify.

### ✔️ Expected result

Theme should be applied

### ❌ Actual result

Error while transferring user.css

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/78131793/130312072-2273dc29-2990-4799-ae41-3b484099283d.png)

**Comment by ps13g** [comment]
The first thing that is wrong in this situation is that the Spicetify Version is at 1.1.0 

Run `spicetify upgrade` and it should upgrade to the latest version of 2.5.0-itsmeow-patch4

After that is done go to the spicetify themes and download all of the new themes since the old ones do not work with the new version 

If you want DribbblishDynamic use this link and download the new version: https://github.com/JulienMaille/dribbblish-dynamic-theme

**Comment by prango71** [comment]
Thank you very much. I downloaded Spicetify from chocolatey so i thought it would be the latest one anyways my bad.
